### ISSUE TITLE
Mutateful app bouncing indefinitely on macOS 10.14.5

### ISSUE THREAD

**Issue by dkordik** [carrierdown/mutateful#14]
Hi- just downloaded the latest release to try this out, and the executable seems to not ever finish loading.
macOS 10.14.5

**Comment by carrierdown** [comment]
Thanks for testing. As I stated in the release notes I haven't been able to test it on OS X yet, but will hopefully be able to get this sorted out soon. 

Alternatively, you could also try building it yourself - it should be quite straightforward. Download .NET Core 3 SDK and run dotnet publish -c Release. Also, you'd need to change Mutate4l.csproj so that it contains <RuntimeIdentifier>osx-x64</RuntimeIdentifier>.

**Comment by Lexvander** [comment]
> Hi- just downloaded the latest release to try this out, and the executable seems to not ever finish loading.
> macOS 10.14.5

I can confirm this. Same OS version, same problem.
Thanks, will try to compile it myself.

**Comment by animatek** [comment]
Hello! same problem here on 10.14.6, i don´t have much idea to compile the app, please if anyone make the compilation can upload or something like that!! or any tutorial of how to compile for noobs ;)

Thank you very much!

**Comment by cooltunes** [comment]
> > Hi- just downloaded the latest release to try this out, and the executable seems to not ever finish loading.
> > macOS 10.14.5
> 
> I can confirm this. Same OS version, same problem.
> Thanks, will try to compile it myself.

I'm on 10.14.6 too, and would love to try out a running version, or learn how to compile it myself. Any pointers? Thx!

**Comment by carrierdown** [comment]
@diemonster Have you tried setting the PublishReadyToRun property to false in Mutate4l.csproj?
Thanks, would love to get some help testing this on Mac.

**Comment by gmuller** [comment]
PublishReadToRun property set to false allows for compilation, executable in the publish folder is ~32MB (sounds about right). Not sitting in front of Live at the moment, but will try to test the compiled artifact works.

**Comment by cooltunes** [comment]
@gmuller i hereby volunteer to test the runtime on osx 10.14.6. if you have a DL link?

**Comment by gmuller** [comment]
Try this on for size: https://www.dropbox.com/s/7i4gj0kfqfspwom/Mutate4l?dl=0

When you start it will start as a terminal application, with this message:

```Welcome to mutateful!
Open Ableton Live, drop mutateful-connector.amxd onto one of the tracks, and start entering formulas.```

**Comment by diemonster** [comment]
Can also confirm that setting `PublishReadToRun` to `false` allows for compilation. However, it looks like formulas are not being parsed on my machine. 

For ex, in Live, when I create a new clip, it will get tagged by column and row correctly, but if I take two clips with note data like `A1` and `A2` and create A3 with the formula `=A3 concat A1 A2`, it's not getting evaluated. 

I might be messing up the syntax here, and if so, my apologies. I tried some other formula examples from the docs and had the same experience.

**Comment by carrierdown** [comment]
@diemonster The correct syntax would be =A1 A2 concat. However, it should report errors if the syntax is broken as well. If you get no output other than the initial welcome-message, this indicates an issue with UDP. Might need to use different ports or something? The defaults are 8022 and 8023, but they can be changed here: /src/Mutate4l/IO/UdpConnector.cs

@dkordik I haven't used Gitter before, but I'm sure that's useful. It's worth a shot at least, I've created one here: https://gitter.im/mutateful/community
Might be difficult timing-wise though, but let's see :)

**Comment by cooltunes** [comment]
> > Try this on for size: https://www.dropbox.com/s/7i4gj0kfqfspwom/Mutate4l?dl=1
> > When you start it will start as a terminal application, with this message:
> > ```
> > Welcome to mutateful!
> > Open Ableton Live, drop mutateful-connector.amxd onto one of the tracks, and start entering formulas.
> > ```
> 
> Sorry, didn't work on 10.14.6. It did display the message you mention, but doesn't do anything else. Activity monitor shows 0 bytes network activity.

Same here. I saw the message, but didn't work on 10.14.6. Anybody else more successful?

**Comment by dkordik** [comment]
Seeing the same when I built locally on 10.15 last night- successful build, but didn't seem to do anything (also wasn't sure if I just didn't know how to use the plugin correctly, so good to see it wasn't just that)

**Comment by diemonster** [comment]
@carrierdown it looks like the `Mutate4l` binary cannot open the UDP port `8022`. While the binary is running, I've tried running `lsof -Pn -i4` to see which UDP/TCP ports are actively open, and `8022` will not show up.

However, if I recompile with the ports set to `31337` and `31338` for receive and send, respectively, I can see that the port is now open:
```
lsof -Pn -i4 | grep 31337
Mutate4l  81436 bivers   27u  IPv4 0xc6f60b67248e2399      0t0  UDP *:31337
```

Unfortunately, when I go back to Ableton with these new ports configured, there's no change in behavior. I also looked at the Max project and tried setting the ports in the `sadam.UdpReceiver` and `sadam.UdpSender` objects, but both of those objects are throwing a `no such object` error.

**Comment by carrierdown** [comment]
@diemonster Thanks for investigating! Have you tried using the mutateful-connector.amxd from the root of this repo, instead of the one contained in the release zip? Cause the one in the released zip is frozen, so might not be too happy interfacing with these externals..

**Comment by diemonster** [comment]
@carrierdown just did. I'm not super familiar with Max, but the `sadam` namespace (?) did not let me specify the udp send/receive externals. So I did this:

<img width="648" alt="Screen Shot 2019-10-30 at 2 38 11 PM" src="https://user-images.githubusercontent.com/12196049/67901003-ec188300-fb22-11e9-9b6e-b352692924ab.png">

That change allowed binding to the ports in question, but when I tried to `concat` clips, `Mutate4l` threw the following error:

```
Unhandled exception. System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR4(Single input, DecCalc& result)
   at Mutate4l.IO.UdpConnector.DecodeData(Byte[] data)
   at Mutate4l.Cli.CliHandler.Start()
   at Mutate4l.Program.Main(String[] args)
[1]    960 abort      ./Mutate4l
```

**Comment by carrierdown** [comment]
@diemonster I see. Might be a problem with the sadam-objects, but the problem with the built-in udp objects are that they don't support sending byte-streams which I'm doing specifically to save as much bandwidth as possible, since UDP messages are limited to around 65kb of data, and some formulas can hit this limit quite easily. It might also be that the sadam objects need some extra files to work properly on Mac. Could be worth a shot to download them and see. http://www.sadam.hu/en/software

**Comment by withakay** [comment]
I have this working on 10.14.6.

The compile error

```
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(307,5): error : Error: compilation failed for "obj/Release/netcoreapp3.0/osx-x64/linked/System.Collections.dll" (0x8007000b) [/Users/bivers/Development/mutateful/src/Mutate4l/Mutate4l.csproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(219,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [/Users/bivers/Development/mutateful/src/Mutate4l/Mutate4l.csproj]

**Comment by diemonster** [comment]
@carrierdown ok, making some progress. I installed the relevant sadam objects in my Max search path and was able to resolve them in the Max patcher. Now getting a different error which is probably an easy fix but I'm just not familiar enough w the codebase yet:

```
watchedclips at 34 set to 36
watchedclips at 35 set to 36
Received 2 clips and formula: [<h1>0] [<h2>1] concat
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): nodename nor servname provided, or not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, String hostname, Int32 port)
   at Mutate4l.IO.UdpConnector.SetClipAsBytesById(Byte[] clipData)
   at Mutate4l.Cli.CliHandler.Start()
   at Mutate4l.Program.Main(String[] args)
[1]    2701 abort      ./Mutate4l
```

**Comment by diemonster** [comment]
@carrierdown also: apologies if you already know this, but according to the Sadam docs, you'll need to include *.mxo compiled externals for the MacOS distributions of Mutateful.

**Comment by withakay** [comment]
> @carrierdown also: apologies if you already know this, but according to the Sadam docs, you'll need to include *.mxo compiled externals for the MacOS distributions of Mutateful.

This.
Installing the madam extensions correctly (but adding just the mxo6 folder to the max search path) along with my comment about `PublishTrimmed` above has it working for me.

Inputting bad formulas crashes the app which is all to easy to do, but that is a different issue :)

**Comment by diemonster** [comment]
@withakay nice one! I can also confirm that `Mutate4l` is receiving events with the mxo files included and `PublishTrimmed=false`. This is using the default ports of `8022/8023` as well. 

I'm still not able to get any formulas to run successfully, though. Still getting the same error as https://github.com/carrierdown/mutateful/issues/14#issuecomment-548137372

**Comment by withakay** [comment]
@diemonster it would appear that on your machine `System.Net.Dns.GetHostAddresses()` cannot resolve `localhost`.

You could try looking in `/etc/hosts` maybe there is an issue there, do you have a line like `127.0.0.1       localhost` or you could try editing UdPClient.Send calls to use the loopback address directly, replacing 
```udpClient.Send(message, message.Length, "localhost", SendPort);```
 with something like 
```udpClient.Send(message, message.Length, new IPEndPoint(IPAddress.Parse("127.0.0.1"), SendPort));```

**Comment by diemonster** [comment]
@withakay lol 🤦‍♂thanks, works w entry in `/etc/hosts`. So weird that MacOS doesn't resolve `localhost` to `127.0.0.1` by default. The params set in the Max object reference `127.0.0.1` specifically, so I guess the code (or Sadam) must use name resolution elsewhere. 

Anyway, no longer getting unhandled exceptions, but formulas are not updating clips either. Will mess around a bit more this evening...

**Comment by withakay** [comment]
Glad I could help :)

> So weird that MacOS doesn't resolve localhost to 127.0.0.1 by default.  

By default there is an entry in the hosts file, something external must have messed yours up :-/

> Anyway, no longer getting unhandled exceptions, but formulas are not updating clips either. Will mess around a bit more this evening...

I have found that I needed to reload the m4l device sometimes, in particular it doesn't recover connections, so start the dotnet app and then load the m4l device.

**Comment by carrierdown** [comment]
I've just tried this on MacOS 10.15.1 and I've gotten it to work (sort of). I copied the mxo-files as stated earlier in this thread, and initially nothing seemed to work, but clicking on the edit device button triggers loading of the externals it seems and I had to fight a bit with the safety features in Catalina which I eventually managed to allow. As soon as this was done things are working, _but_ the device needs to be in edit mode or it won't work. I have no idea why this is, seems like a Max quirk if you ask me.

**Comment by carrierdown** [comment]
Update: It's working now without needing to have the device in edit mode. The problem is with the externals and freezing the m4l device. Once unfrozen and re-saved, things are working great, but if I try to freeze the device I get an error on the mxo-versions of the objects saying that they couldn't be added.

**Comment by carrierdown** [comment]
Update 2: Ok, I managed to successfully freeze the device after restarting Max again. Things are working fine at my end now, and I've added a mutateful-v1.0-osx-fixed.zip to the assets for the mutateful v1.0 release. Would be great if as many people as possible could test this on their systems as well. Fingers crossed! :)

**Comment by diemonster** [comment]
`mutateful-v1.0-osx-fixed.zip` appears to be working for me! 

At first I wasn't getting any UDP traffic until I opened the Max patcher, and then a bunch of out-of-order events came streaming through as if they had been sitting in a queue. Closed and re-opened Ableton and parsing worked immediately. I can't repro the behavior from the first attempt so let's chalk that up to something strange on my local machine for now...

thanks @carrierdown, excited to dive into this a bit more 💃

**Comment by cooltunes** [comment]
> `mutateful-v1.0-osx-fixed.zip` appears to be working for me!
> 
> At first I wasn't getting any UDP traffic until I opened the Max patcher, and then a bunch of out-of-order events came streaming through as if they had been sitting in a queue. Closed and re-opened Ableton and parsing worked immediately. I can't repro the behavior from the first attempt so let's chalk that up to something strange on my local machine for now...
> 
> thanks @carrierdown, excited to dive into this a bit more 💃

You guys are awesome! 
[mutateful-v1.0-osx-fixed.zip](https://github.com/carrierdown/mutateful/releases/download/v1.0/mutateful-v1.0-osx-fixed.zip) does also work in Ableton Live 9.7.7 with M4L 8 on OSX 10.14.6. THX!

**Comment by carrierdown** [comment]
Great to hear that it works in Live 9 as well! Cheers!

**Comment by rinckd** [comment]
Can also confirm that mutateful-v1.0-osx-fixed.zip works great in OSX 10.15.1 and Ableton Live 10.1.3. Slick!
